discontinued = [ "NAD+ Cell Regenerator", "Fisetin with Novusetin", "Fisetin Novusetin", "Collagen",]
FILL_EVERY_X_DAYS = 30
LAST_FILL_DATE = "2024-01-16"
[[supps]]
name = "ashwagandha"
bedtime = 600

[[supps]]
name = "aspirin"
lunch = 86
days_per_week = 3

[[supps]]
name = "astaxanthin"
morning = 12

[[supps]]
name = "b complex"
morning = 0.5
days_per_week = 2
units = "caps"

[[supps]]
name = "b-12"
lunch = 1000
units = "mcg"
days_per_week = 1

[[supps]]
name = "boron"
morning = 2

[[supps]]
name = "broccomax"
morning = 1
dinner = 1
units = "caps"

[[supps]]
name = "vitamin c"
morning = 500

[[supps]]
name = "creatine"
lunch = 2.5
days_per_week = 4
units = "g"

[[supps]]
name = "Ca-AKG"
morning = 1000
dinner = 1000

[[supps]]
name = "coq10"
morning = 100
lunch = 100
dinner = 100

[[supps]]
name = "d-3"
morning = 5000
units = "iu"
winter_only = true

[[supps]]
name = "dhea"
morning = 25

[[supps]]
name = "vitamin e"
morning = 67
days_per_week = 3

[[supps]]
name = "EPA/DHA"
morning = 1280
dinner = 640

[[supps]]
name = "garlic"
morning = 1200
dinner = 1200

[[supps]]
name = "genistein"
morning = 125

[[supps]]
name = "ginger root"
morning = 2200
dinner = 2200

[[supps]]
name = "glucosamine sulfate"
morning = 1500
dinner = 1500

[[supps]]
name = "glycine"
morning = 2000

[[supps]]
name = "hyaluronic acid"
morning = 300

[[supps]]
name = "iodine"
morning = 0.126
units = "ml"

[[supps]]
name = "iron"
morning = 10

[[supps]]
name = "k1"
morning = 1500
units = "mcg"

[[supps]]
name = "k2-mk7"
morning = 300
units = "mcg"

[[supps]]
name = "k2-mk4"
morning = 5

[[supps]]
name = "l-lysine"
morning = 1000
dinner = 1000

[[supps]]
name = "l-tyrosine"
dinner = 500

[[supps]]
name = "lithium orotate"
morning = 1000
units = "mcg"

[[supps]]
name = "lycopene"
morning = 10

[[supps]]
name = "magnesium slow release"
morning = 1
units = "caps"

[[supps]]
name = "magnesium taurate"
bedtime = 125

[[supps]]
name = "magnesium glycinate"
bedtime = 350

[[supps]]
name = "magtein"
bedtime = 2000

[[supps]]
name = "methyl folate"
morning = 1700
units = "mcg"

[[supps]]
name = "nac"
morning = 1800
dinner = 1800

[[supps]]
name = "pqq"
morning = 20

[[supps]]
name = "probiotic"
morning = 1
units = "caps"

[[supps]]
name = "taurine"
morning = 2000
dinner = 1000

[[supps]]
name = "turmeric"
morning = 1000
dinner = 1000

[[supps]]
name = "zeaxanthin"
morning = 20
days_per_week = 3

[[supps]]
name = "zinc"
morning = 15

[product_aliases]
"Naturally Sourced Vitamin E" = "vitamin e"
"Natural Vitamin K2 MK-7 with MenaQ7" = "k2-mk7"
"Liquid D-3 & MK-7" = "d-3"
"Calcium AKG Longevity" = "ca-akg"
"MK-7 Vitamin K-2" = "k2-mk7"
"Optimized Folate" = "methyl folate"
"Extend-Release Magnesium" = "magnesium slow release"
Crucera-SGS = "broccomax"
B-50 = "b complex"
"Vitamin K2, MK-4 (Menatetrenone)" = "k2-mk4"
"Super K" = "k1"
"Ultimate Omega, Lemon" = "epa/dha"
"Ultimate Omega" = "epa/dha"
Lithium = "lithium orotate"
